# Generated by Django 2.0.6 on 2018-06-19 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('houseNumber', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('zipCode', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIn', models.DateField()),
                ('checkOut', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.IntegerField()),
                ('expirationYear', models.IntegerField()),
                ('expirationMonth', models.IntegerField()),
                ('cvvCode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('photoUrl', models.ImageField(default=None, null=True, upload_to='')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='IncludedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('NONE', 'No services'), ('TELEPHONE', 'Telephone'), ('GARAGE', 'Garage'), ('WIFI', 'Wifi'), ('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('BRUNCH', 'Brunch')], default='NONE', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('cf', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('hotelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelKeeper',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookingApp.Person')),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            bases=('bookingApp.person',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookingApp.Person')),
            ],
            bases=('bookingApp.person',),
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Address'),
        ),
        migrations.AddField(
            model_name='includedservice',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='roomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.Room'),
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookingApp.User')),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            bases=('bookingApp.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='creditCard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingApp.CreditCard'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotelKeeperId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.HotelKeeper'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingApp.User'),
        ),
    ]
