# Generated by Django 2.0.5 on 2018-06-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0002_room_roomnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cardNumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cvvCode',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expirationMonth',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expirationYear',
            field=models.CharField(max_length=4),
        ),
    ]
