# Generated by Django 2.0.6 on 2018-06-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0003_auto_20180620_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='photoUrl',
            field=models.ImageField(default=None, null=True, upload_to='static/img'),
        ),
    ]
