# Generated by Django 2.0.6 on 2018-06-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0004_auto_20180620_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='photoUrl',
            field=models.CharField(max_length=2550),
        ),
    ]
