# Generated by Django 2.0.6 on 2018-06-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0005_auto_20180621_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creditCard',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookingApp.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photoUrl',
            field=models.ImageField(default=None, null=True, upload_to='static/img'),
        ),
    ]
