# Generated by Django 2.0.6 on 2018-06-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApp', '0006_auto_20180622_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='includedservice',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='services',
            field=models.ManyToManyField(to='bookingApp.IncludedService'),
        ),
    ]
